# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47316236cb142a8267809a59cf11afa76d71405cf3e7050e81b53b9cdfa65f2b61b80aad2a6b847d7030b421dede2d84277c7b0df2e4dc03bff53721cafd79b8

test:
  secret_key_base: bd36d1d629c05e77b3a43f891e980cc4d34ec614305b3d39f361ee13945a5aab3d86fd8efded53572606713163cb121ab5e5368932a73c74de7ae7caafd65a29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
